# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PkVEg2MqSwxNhBeRKf-6rKqvPhyGdJU
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import cv2  # OpenCV for high-speed image loading
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# This line ensures plots show up directly in the notebook
# %matplotlib inline

# Check if everything is connected correctly
print(f"TensorFlow version: {tf.__version__}")
print(f"OpenCV version: {cv2.__version__}")

import kagglehub

# Download latest version
path = kagglehub.dataset_download("ravirajsinh45/real-life-industrial-dataset-of-casting-product")

print("Path to dataset files:", path)

# Training Set (80%) - For training model
train_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(path,'casting_data/casting_data/train'),
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(224,224),
    batch_size=32
)

# Validation Set (20%) - Used to tune the model
val_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(path,'casting_data/casting_data/train'),
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(224,224),
    batch_size=32
)

# Test Set - For Unbiased Performance Estimate
test_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(path,'casting_data/casting_data/test'),
    image_size=(224,224),
    batch_size=32
)

# Creating a rescaling layer
normalization_layer = tf.keras.layers.Rescaling(1./255)

# Apply rescaling and prefetching datasets
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y)).cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.map(lambda x, y: (normalization_layer(x), y)).cache().prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.map(lambda x, y: (normalization_layer(x), y)).cache().prefetch(buffer_size=AUTOTUNE)

model = tf.keras.models.Sequential([
    # First Conv Block
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu',input_shape=(224, 224, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),

    # Second Conv Block
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),

    # Third Conv Block
    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),

    # Flatten and Dense Layers
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid') # Sigmoid for Binary Classification
])

model.summary()

model.compile(
    optimizer='adam',
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy']
)

EPOCHS = 10

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

loss, accuracy = model.evaluate(test_ds)
print(f"Final Test Accuracy: {accuracy*100:.2f}%")

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(EPOCHS)

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend()
plt.show()

from sklearn.metrics import classification_report, confusion_matrix
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = (model.predict(test_ds) > 0.5).astype("int32").flatten()

print(classification_report(y_true, y_pred))

import seaborn as sns

cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt='d')

# Comparison with MobilNetV2 based model (Transfer Learning)
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)
model2 = tf.keras.models.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# All layers except last 20 in the model frozen
base_model.trainable = True

for layer in base_model.layers[:-20]:
    layer.trainable = False

model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model2.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

from sklearn.metrics import classification_report
import numpy as np

y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = (model2.predict(test_ds) > 0.5).astype("int32")

print(classification_report(y_true, y_pred))

import seaborn as sns

cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt='d')

model.save('custom_cnn.h5')

model2.save('mobilenet_v2.h5')

